#!/bin/bash
# Delete unused images and backup directories
# Generated by analyze_image_usage.js

echo "🗑️  Deleting unused images and backup directories..."

# Delete backup directory: optimized
rm -rf "public/optimized"
# Delete large image: optimized/img.webp
rm "public/optimized/img.webp"
# Delete large image: minimeals_cardhome.png
rm "public/minimeals_cardhome.png"
# Delete large image: optimized/minimeals_cardhome.webp
rm "public/optimized/minimeals_cardhome.webp"
# Delete backup directory: original_backup_optimized
rm -rf "public/original_backup_optimized"

echo "✅ Cleanup complete!"
echo "💰 Space saved: 11.99MB"
