console.log('📧 SETTING UP SENDGRID EMAIL SERVICE FOR SUPABASE');
console.log('');
console.log('🚀 STEP 1: Create SendGrid Account');
console.log('1. Go to https://sendgrid.com');
console.log('2. Click "Start for Free"');
console.log('3. Sign up with your email');
console.log('4. Verify your email address');
console.log('');
console.log('🔑 STEP 2: Get API Key');
console.log('1. In SendGrid Dashboard, go to Settings → API Keys');
console.log('2. Click "Create API Key"');
console.log('3. Name it: "Supabase Auth"');
console.log('4. Select "Full Access" or "Restricted Access" (Mail Send)');
console.log('5. Click "Create & View"');
console.log('6. COPY THE API KEY (you won\'t see it again!)');
console.log('');
console.log('📧 STEP 3: Verify Sender Email');
console.log('1. In SendGrid Dashboard, go to Settings → Sender Authentication');
console.log('2. Click "Verify a Single Sender"');
console.log('3. Fill in your details:');
console.log('   - From Name: Your Name or Company Name');
console.log('   - From Email: your-email@domain.com');
console.log('   - Company: Your Company');
console.log('   - Address: Your Address');
console.log('4. Click "Create"');
console.log('5. Check your email and click the verification link');
console.log('');
console.log('⚙️ STEP 4: Configure Supabase SMTP');
console.log('1. Go to your Supabase Dashboard');
console.log('2. Navigate to Authentication → SMTP Settings');
console.log('3. Enable "Custom SMTP"');
console.log('4. Fill in these details:');
console.log('   - Host: smtp.sendgrid.net');
console.log('   - Port: 587');
console.log('   - Username: apikey');
console.log('   - Password: [Your SendGrid API Key from Step 2]');
console.log('   - Sender Email: [Your verified email from Step 3]');
console.log('5. Click "Save"');
console.log('');
console.log('✅ STEP 5: Test Configuration');
console.log('1. Go to Authentication → Settings');
console.log('2. Ensure "Confirm email" is enabled');
console.log('3. Test with a new signup');
console.log('4. Check if verification email is received');
console.log('');
console.log('🎯 STEP 6: Remove Temporary Fix');
console.log('Once emails are working, remove the auto-confirm code from useAuth.tsx');
console.log('');
console.log('📊 SendGrid Pricing:');
console.log('- Free Tier: 100 emails/day (perfect for testing)');
console.log('- Starter: $14.95/month for 50,000 emails/month');
console.log('- Professional: $89/month for 100,000 emails/month');
console.log('');
console.log('🔍 Troubleshooting:');
console.log('- Check spam folder for test emails');
console.log('- Verify API key is correct');
console.log('- Ensure sender email is verified');
console.log('- Check Supabase logs for errors');
console.log('');
console.log('📞 Need Help?');
console.log('- SendGrid Support: support@sendgrid.com');
console.log('- Supabase Support: https://supabase.com/support');
console.log('- Check Supabase Dashboard → Authentication → Logs');
